package eu.europa.ec.fisheries.schema.config.module.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-07-06T11:53:21.965+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1", name = "ConfigModulePortType")
@XmlSeeAlso({ObjectFactory.class, eu.europa.ec.fisheries.schema.config.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConfigModulePortType {

    @WebResult(name = "SingleSettingResponse", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "SetSetting")
    public SingleSettingResponse setSetting(
        @WebParam(partName = "body", name = "SetSettingRequest", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1")
        SetSettingRequest body
    ) throws ConfigFault;

    @WebResult(name = "PullSettingsResponse", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "PullSettings")
    public PullSettingsResponse pullSettings(
        @WebParam(partName = "body", name = "PullSettingsRequest", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1")
        PullSettingsRequest body
    ) throws ConfigFault;

    @WebResult(name = "PushSettingsResponse", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "PushSettings")
    public PushSettingsResponse pushSettings(
        @WebParam(partName = "body", name = "PushSettingsRequest", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1")
        PushSettingsRequest body
    ) throws ConfigFault;

    @WebResult(name = "SettingsListResponse", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetSetting")
    public SettingsListResponse getSetting(
        @WebParam(partName = "body", name = "ListSettingsRequest", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1")
        ListSettingsRequest body
    ) throws ConfigFault;

    @WebResult(name = "SingleSettingResponse", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "ResetSetting")
    public SingleSettingResponse resetSetting(
        @WebParam(partName = "body", name = "ResetSettingRequest", targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1")
        ResetSettingRequest body
    ) throws ConfigFault;
}
