package eu.europa.ec.fisheries.schema.config.module.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-07-06T11:53:22.001+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ConfigModuleService", 
                  wsdlLocation = "file:/C:/uvms-git-test/models/ConfigModule/src/main/resources/contract/ConfigModuleService.wsdl",
                  targetNamespace = "urn:module.config.schema.fisheries.ec.europa.eu:v1") 
public class ConfigModuleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:module.config.schema.fisheries.ec.europa.eu:v1", "ConfigModuleService");
    public final static QName ConfigModulePortType = new QName("urn:module.config.schema.fisheries.ec.europa.eu:v1", "ConfigModulePortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/uvms-git-test/models/ConfigModule/src/main/resources/contract/ConfigModuleService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConfigModuleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/uvms-git-test/models/ConfigModule/src/main/resources/contract/ConfigModuleService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConfigModuleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConfigModuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConfigModuleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigModuleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigModuleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConfigModuleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConfigModulePortType
     */
    @WebEndpoint(name = "ConfigModulePortType")
    public ConfigModulePortType getConfigModulePortType() {
        return super.getPort(ConfigModulePortType, ConfigModulePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfigModulePortType
     */
    @WebEndpoint(name = "ConfigModulePortType")
    public ConfigModulePortType getConfigModulePortType(WebServiceFeature... features) {
        return super.getPort(ConfigModulePortType, ConfigModulePortType.class, features);
    }

}
