package eu.europa.ec.fisheries.schema.config.source.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-07-06T11:53:22.932+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", name = "ConfigDataSourcePortType")
@XmlSeeAlso({eu.europa.ec.fisheries.schema.config.types.v1.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConfigDataSourcePortType {

    @WebResult(name = "SingleSettingResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "UpdateSetting")
    public SingleSettingResponse updateSetting(
        @WebParam(partName = "body", name = "UpdateSettingRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        UpdateSettingRequest body
    ) throws ConfigFault;

    @WebResult(name = "SingleSettingResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "DeleteSetting")
    public SingleSettingResponse deleteSetting(
        @WebParam(partName = "body", name = "DeleteSettingRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        DeleteSettingRequest body
    ) throws ConfigFault;

    @WebResult(name = "SettingsListResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "CreateAllSettings")
    public SettingsListResponse createAllSettings(
        @WebParam(partName = "body", name = "CreateAllSettingRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        CreateAllSettingRequest body
    ) throws ConfigFault;

    @WebResult(name = "SingleSettingResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetSetting")
    public SingleSettingResponse getSetting(
        @WebParam(partName = "body", name = "GetSettingRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        GetSettingRequest body
    ) throws ConfigFault;

    @WebResult(name = "GetSettingsCatalogResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetSettingsCatalog")
    public GetSettingsCatalogResponse getSettingsCatalog(
        @WebParam(partName = "body", name = "GetSettingsCatalogRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        GetSettingsCatalogRequest body
    ) throws ConfigFault;

    @WebResult(name = "SingleSettingResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "CreateSetting")
    public SingleSettingResponse createSetting(
        @WebParam(partName = "body", name = "CreateSettingRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        CreateSettingRequest body
    ) throws ConfigFault;

    @WebResult(name = "SettingsListResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetGlobalSettings")
    public SettingsListResponse getGlobalSettings(
        @WebParam(partName = "body", name = "GetGlobalSettingsRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        GetGlobalSettingsRequest body
    ) throws ConfigFault;

    @WebResult(name = "SettingsListResponse", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "ListSettings")
    public SettingsListResponse listSettings(
        @WebParam(partName = "body", name = "ListSettingsRequest", targetNamespace = "urn:source.config.schema.fisheries.ec.europa.eu:v1")
        ListSettingsRequest body
    ) throws ConfigFault;
}
